version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - tests_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 10
  tests:
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src/
    depends_on:
      db:
        condition: service_healthy
    command: "pytest -vv"
    networks:
      - tests_network

networks:
  tests_network:
    name: tests_network
