version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - db:/var/lib/postgresql/data/
      # - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - web_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src/
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - web_network

volumes:
  db:


networks:
  web_network:
    name: web_network
