version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - web_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/app/src/
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - web_network

volumes:
  db:


networks:
  web_network:
    name: web_network
