version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - web_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:latest
    env_file:
      - ./.env
    ports:
      - "6379:6379"
    networks:
      - web_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 100

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src/
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - web_network

volumes:
  db:


networks:
  web_network:
    name: web_network
