version: '3.8'
services:
  tests:
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src/
    command: "pytest -vv"
    networks:
      - tests_network

networks:
  tests_network:
    external:
      name: web_network
